rocketmq:
  isOnOff: on
  producer:
    #发送同一类消息的设置为同一个group，保证唯一,默认不需要设置，rocketmq会使用ip@pid(pid代表jvm名字)作为唯一标示
    groupName: fzyac
    #mq的nameserver地址
    namesrvAddr: 192.168.2.33:9876
    #消息最大长度 默认1024*4(4M)
    maxMessageSize: 4096
    #发送消息超时时间,默认3000
    sendMsgTimeout: 3000
    #发送消息失败重试次数，默认2
    retryTimesWhenSendFailed: 2
spring:
  http:
    ecoding:
      charset: UTF-8
      enabled: true
      force: true
  mvc:
    throw-exception-if-no-handler-found: true
    favicon:
      enabled: false
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.2.8:3306/fzyac?serverTimezone=Asia/Shanghai&useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    #url: jdbc:mysql://rm-wz9y11n90irpygeo5.mysql.rds.aliyuncs.com:3306/fzyac?serverTimezone=Asia/Shanghai&useSSL=false&useUnicode=true&characterEncoding=utf-8
    #username: beehive
    #password: Ru2kKCH6GEoWYptJ
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000  # ????????????????????
    timeBetweenEvictionRunsMillis: 60000 # ???ü????ò??????μ??????????????????????λ?????
    minEvictableIdleTimeMillis: 30000  # ??????????????????С??????????λ?????
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true # ??PSCache??????????????????PSCache???С
    maxPoolPreparedStatementPerConnectionSize: 20

mybatis:
  mapper-locations: classpath:mapper/*/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 9006