
rocketmq:
  consumer:
    isOnOff: on
    groupName: fzyac
    namesrvAddr: 192.168.2.33:9876
    #该消费者订阅的主题和tags("*"号表示订阅该主题下所有的tags),格式：topic~tag1||tag2||tag3;topic2~*;
    topics: fzyac-topic~*
    consumeThreadMin: 20
    consumeThreadMax: 64
    #设置一次消费消息的条数，默认为1条
    consumeMessageBatchMaxSize: 1
server:
  port: 9005


elasticsearch:
  ip: 192.168.2.2
  port: 9300
  cluster:
    name: elasticsearch
  pool: 100